const mongoose=require("mongoose");
const userSchema=new mongoose.Schema(
    {
        firstName:{
            type:String,
            required:true,
            minLength:4,
            maxLength:50,
        },
        lastName:{
            type:String,
        },
        emailId:{
            type:String,
            lowercase:true,
            required:true,
            unique:true,
            trim:true,
            validate(value){
                if(!validator.isEmail())
            }
        },
        password:{
            type:String,
        },
        age:{
            type:Number,
        },
        gender:{
            type:String,
        },
    }
);
module.exports=mongoose.model("User",userSchema);